Repository SucceSS-team-13/BE, pull requests merged in 2025-02, with the labels that each got.

#21 Feat/#7 채팅방 생성, 삭제, 채팅내역 조회
  src/main/java/com/example/SucceSS/apiPayload/ApiResponse.java
  src/main/java/com/example/SucceSS/repository/ChatRepository.java
  src/main/java/com/example/SucceSS/service/ChatService/ChatRoomService.java
  src/main/java/com/example/SucceSS/web/controller/ChatController.java
  src/main/java/com/example/SucceSS/web/dto/ChatDto.java
Labels: ✨feature

#19 [Feat] 회원 정보 입력 및 결과 조회 API 구현
  src/main/java/com/example/SucceSS/domain/Member.java
  src/main/java/com/example/SucceSS/domain/enums/AgeGroup.java
  src/main/java/com/example/SucceSS/domain/enums/DetailedHobby.java
  src/main/java/com/example/SucceSS/domain/enums/Hobby.java
  src/main/java/com/example/SucceSS/domain/enums/HobbyCategory.java
  src/main/java/com/example/SucceSS/domain/enums/PersonalityEnergy.java
  src/main/java/com/example/SucceSS/domain/enums/PersonalityJudgement.java
  src/main/java/com/example/SucceSS/service/MemberService/MemberService.java
  src/main/java/com/example/SucceSS/web/controller/MemberController.java
  src/main/java/com/example/SucceSS/web/dto/MemberRequestDto.java
  src/main/java/com/example/SucceSS/web/dto/MemberResponseDto.java
  src/main/resources/application.properties
Labels: ✨feature

#26 Feat/#7 chat room 채팅방 조회, 채팅 전송 테스트, StompHandler, StompErrorHandler 추가
  src/main/java/com/example/SucceSS/config/chat/Kafka/KafkaConfig.java
  src/main/java/com/example/SucceSS/config/chat/Kafka/KafkaConsumer.java
  src/main/java/com/example/SucceSS/config/chat/StompErrorHandler.java
  src/main/java/com/example/SucceSS/config/chat/StompHandler.java
  src/main/java/com/example/SucceSS/config/chat/WebSocketConfig.java
  src/main/java/com/example/SucceSS/config/security/JwtProvider.java
  src/main/java/com/example/SucceSS/domain/ChatRoom.java
  src/main/java/com/example/SucceSS/repository/ChatRoomRepository.java
  src/main/java/com/example/SucceSS/service/ChatService/ChatRoomService.java
  src/main/java/com/example/SucceSS/utils/GetCurrentUser.java
  src/main/java/com/example/SucceSS/utils/JwtUtils.java
  src/main/java/com/example/SucceSS/web/controller/ChatController.java
  src/main/java/com/example/SucceSS/web/dto/ChatRoomResponseDto.java
Labels: ✨feature

#27 Feat/#7 chat room StompErrorHandler 수정, 한국 표준시로 응답하도록 수정
  src/main/java/com/example/SucceSS/config/chat/Kafka/KafkaConsumer.java
  src/main/java/com/example/SucceSS/config/chat/Kafka/KafkaProducer.java
  src/main/java/com/example/SucceSS/config/chat/StompErrorHandler.java
  src/main/java/com/example/SucceSS/config/chat/StompHandler.java
  src/main/java/com/example/SucceSS/config/security/JwtProvider.java
  src/main/java/com/example/SucceSS/domain/Chat.java
  src/main/java/com/example/SucceSS/service/ChatService/ChatService.java
  src/main/java/com/example/SucceSS/web/dto/ChatDto.java
Labels: ✨feature, 🐛fix

#36 [Fix] 도커 배포 중 mysql 접속 문제 해결
  .github/workflows/dev-gradle.yml
Labels: 🐛fix

#49 [Fix] 취미, 세부취미 null 처리 추가
  src/main/java/com/example/SucceSS/service/MemberService/MemberService.java
  src/main/java/com/example/SucceSS/web/dto/MemberRequestDto.java
Labels: 🐛fix

#53 [Fix] 컬렉션 교체 -> 요소 추가 및 삭제로 변경
  src/main/java/com/example/SucceSS/domain/Member.java
Labels: 🐛fix

#54 [Fix] DB 반영 에러 수정
  src/main/java/com/example/SucceSS/domain/Member.java
  src/main/java/com/example/SucceSS/service/MemberService/MemberService.java
Labels: 🐛fix

#55 [Fix] DB 강제 주입 코드 제거
  src/main/java/com/example/SucceSS/service/MemberService/MemberService.java
Labels: 🐛fix

#56 [Chore] ENUM 값 오타 수정
  src/main/java/com/example/SucceSS/domain/enums/DetailedHobby.java
  src/main/java/com/example/SucceSS/domain/enums/Hobby.java
Labels: 🐛fix

#63 feat/#58 채팅방 목록 조회 api에 키워드 검색 추가
  src/main/java/com/example/SucceSS/repository/ChatRoomRepository.java
  src/main/java/com/example/SucceSS/service/ChatService/ChatRoomService.java
  src/main/java/com/example/SucceSS/web/controller/ChatController.java
Labels: ✨feature

#67 [Fix] SSL 인증 추가
  docker-compose.yml
  src/main/java/com/example/SucceSS/config/CorsConfig.java
  src/main/resources/application.properties
Labels: 🐛fix

#69 [Fix] kakao redirect uri 수정
  src/main/resources/application.properties
Labels: 🐛fix
